### PR TITLE
New community script

### PR DESCRIPTION
**Pull request by mikkorautiainen**
Please checkout my script. 
It installs a proxy and index page that combines Fauxton, RabbitMQ's plugin and HAProxy's status page under one site.

### CODE REVIEW

**Comment by lazedo** [comment]
@mikkorautiainen pretty awesome, thanks!
the certificate files (key and cert) should not be included right ?
maybe a link to https://letsencrypt.org/ ?

**Comment by mikkorautiainen** [comment]
I think the user can install their own certs if they want, but it’s good to have something so they can get going immediately.
It would be easy for me to modify the installer, so it generates the self-signed cert for the user. Then the certs would always be unique.
Anyway, it is impossible to get a letsencrypt-cert for a private address or localhost, so that excludes most of the use cases.

Maybe it stupid to have cert on a service that is (in most cases) only accessible though SSH, but old habits die hard :)

**Comment by lazedo** [comment]
"It would be easy for me to modify the installer, so it generates the self-signed cert for the user."
yes, please.
letsencrypt was a suggestion.

**Comment by mikkorautiainen** [comment]
@lazedo thanks, good call! 
Distributing pre-generated certificates is not good security practice and the install directory is much cleaner now.

**Comment by lazedo** [comment]
@mikkorautiainen thank you!!

**Comment by jamesaimonetti** [comment]
@mikkorautiainen thanks, this is awesome!

**Pull request merged**
