### PR TITLE
Added cdr-mysql-processor

### PR DESCRIPTION
**Pull request by kalda341**

### CODE REVIEW

**Comment by k-anderson** [comment]
@kalda341 Howdy :)  

This is something that I have seen a few requests for in the community, I appreciate you contributing it back!  I just have one questions before accepting, there doesn't seem to be any documentation on how you are creating the CDRs as files on the system.  The parser looks like it wants the Kazoo format but the CDR app does not have a feature to write them to the disk :)

**Comment by kalda341** [comment]
I have written a Kazoo app that writes them to disk. I originally had had this script listening in on the AMQP stream itself, but for various reasons we decided it was better to load them from the filesystem. I would be happy to contribute this back to the community - how do you want it? I figure it is probably not an app you would want in the standard Kazoo build.
This script works well but it turns out the call_ids are not unique, so I'll need to find a new primary key.
 I am now building a simple API that allows statistics to be retrieved and graphed from this data.

**Comment by fenollp** [comment]
This could be part of the `cdr` app and like the CSV dump, be a SQL dump.

**Comment by kalda341** [comment]
This doesn't quite meet our needs as we want this running constantly, updating the database in real time. The talk "Billing Data with Kazoo" at KazooCon 2015 implied that the AMQP way was the preferred way of getting CDRs. Getting this data through the API doesn't quite fit our requirements.
Or am I misunderstanding what you mean? Do you mean dumping them to file in real time? I considered this option before writing this but decided another script would need to be used to insert them into the database anyway. Additionally, there would have to be some kind of mapping between the AMQP fields and the database fields, which might as well just be done in the script.

I have created a pull request for cdrtofile here: https://github.com/2600hz/kazoo/pull/1536

**Comment by avneet17** [comment]
when run "python2 run.py"  it shows

INFO:MySQLClient:Connecting to MySQL database
 242 pyinotify ERROR] add_watch: cannot watch /tmp/cdrs WD=-1, Errno=No such file or directory (ENOENT)
ERROR:pyinotify:add_watch: cannot watch /tmp/cdrs WD=-1, Errno=No such file or directory (ENOENT)
INFO:newCDRHandler:Searching /tmp/cdrs for existing CDRs
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    main()
  File "run.py", line 12, in main
    watch.process_existing()
  File "/root/community-scripts/cdr-mysql-processor/directory_watcher.py", line 84, in process_existing
    files_in_dir = [join(path, f) for f in listdir(path) if isfile(join(path, f))]
OSError: [Errno 2] No such file or directory: '/tmp/cdrs'

so where to add cdrtofile and which script to add.

**Comment by kalda341** [comment]
The directories need to be created with the correct permissions before
running the script. This should probably be handled by the script, but
currently isn't.
Both the kazoo user, and the user the script is running under need write
permissions.

**Comment by avneet17** [comment]
thanks for reply, but where to give and write kazoo permissions.

**Comment by kalda341** [comment]
I run both the script and Kazoo (obviously) on the kazoo user. All three
directories are owned by the kazoo user and have 755 permissions.

**Pull request merged**
